### ISSUE TITLE
Request: Add @self-admin redirect support to edit the page in admin panel

### ISSUE THREAD

**Issue by Blazeflack** [bleutzinn/grav-plugin-add-page-by-form#31]
Hi.

I would like to request a redirect option of '@self-admin' like you currently have for '@self', only that it should open the page for editing in the admin panel.

My current use case is that I need an easy way to create a page (blog post) with all the frontmatter defined already. I then need a good place to put some content into the post, but unfortunately the simple editor is on the front end is not good enough for this. I need to use the admin editing where a plugin for a more advanced editor has effect.

Thank you for the plugin and your time.

**Comment by bleutzinn** [comment]
One way would be to introduce a new 'pageconfig' block frontmatter variable: `redirect_prefix`. If that is set to `admin/pages` the new page will open in the backend. The only problem is that the user needs to login into the backend. That is something my plugin can not handle because the frontend and backend authentication are fully separated in Grav.

**Comment by Blazeflack** [comment]
That would be sufficient for my specific use case and support other use cases easily too.

Having an additional login process after the redirect is not a major issue for me. It is what it is.

Thanks for your time.

**Comment by bleutzinn** [comment]
The new pageconfig block variable `redirect_prefix` has been added to the "self-admin" branch. To test things just replace your current `add-page-by-form.php` file by the one in the "self-admin" branch.

This is the complete form page I used for testing:
```
---
routable: true
title: 'Submit assignment for review'
template: form
visible: true
pageconfig:
    parent: /submitted-assignments/cmpt363-e100/drafts
    subroute: tja/geen_idee
    redirect_prefix: admin/pages
pagefrontmatter:
    visible: true
    status: draft
    template: default
    course:
        assignment: 'CMPT363 E100'
    instructor:
        name: 'Jane Doe'
form:
    name: addpage-assignment-cmpt363-e100
    fields:
        -
            name: name
            label: Name
            type: text
            validate:
                required: true
        -
            name: title
            label: Title
            type: text
            validate:
                required: true
        -
            name: content
            label: 'Assignment text'
            type: textarea
            size: long
            classes: editor
            validate:
                required: true
        -
            name: attachments
            label: 'Attachment (PDF only)'
            type: file
            multiple: true
            destination: '@self'
            accept:
                - application/pdf
            validate:
                required: false
        -
            name: honeypot
            type: honeypot
    buttons:
        -
            type: submit
            value: Submit
    process:
        -
            addpage: null
        -
            redirect: '@self'
---

Please write your assignment and attach any images and/or files.
```

I hope this fulfils your request. Please let me know.
