### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by bobrocke** [bleutzinn/grav-plugin-add-page-by-form#34]
When the plug-in is enabled, Grav throws the following error:

Server Error
Sorry, something went terribly wrong!

0 - The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 8 (near "items: @self.children").

Where should I start looking to fix this?

**Comment by bleutzinn** [comment]
I've just tried the plugin using the latest Grav version and it works well. Can you post your form page frontmatter? Make sure you enclose it in triple ticks:  ```

**Comment by bobrocke** [comment]
Here it is:
```
---
title: 'Add Blog Post'
template: form
pageconfig:
    parent: '/blog'
    include_username: false
    overwrite_mode: false
pagefrontmatter:
    template: item
    title: My new Blog post
    taxonomy:
        category: blog
        tag: [journal, guest]
form:
    name: addpage.blogpost
    fields:
        -
            name: author
            label: 'Author'
            type: text
        -
            name: title
            label: 'Post Title'
            type: text
        -
            name: taxonomy.tag
            label: 'Tags (comma separated)'
            type: text
        -
            name: content
            label: 'Post Content'
            type: textarea
            size: long
            classes: editor
            size: long
        -
            name: images
            label: 'Images to upload'
            type: file
            multiple: true
            accept:
                - 'image/*'
            destination: '@self'
        -
            name: honeypot
            type: honeypot
    buttons:
        -
            type: submit
            value: Submit
    process:
        -
            addpage: null
        -
            redirect: '/blog'
---

## New Blog Post

Write your blog post:
```

Thanks for the quick response!
