### ISSUE TITLE
delete some text from page header

### ISSUE THREAD

**Issue by abooks23** [bleutzinn/grav-plugin-add-page-by-form#41]
Hi !
i set array in php
```
    public static function avto()
    {
        return array (
            'lada' => 'lada',
            'ford' => 'ford',
            'lancia' => 'lancia',
        );
    }
```
and in form
   
 ```
        name: avto
            type: checkboxes
            label: 'Avto'
            data-options@: '\Grav\Theme\Quark::avto'
```
on new page created with plugin I see
```
avto:
    avto-lada: lada
    avto-ford: ford
    avto-lancia: lancia
```
if I set form.md normal without php array

      ```
      name: 'Avto'
            type: checkboxes
           classes: check
            options:
                - lada
                - ford
                - lancia
```
 after   submiting I see that in new page
```
Avto:
    Avto-0: '0'
    Avto-1: '1'
    Avto-2: '2'
```
how I can remove  `avto-lada:` and other on page header
need
```
avto:
     lada
     ford
     lancia
```
