### ISSUE TITLE
Call to undefined method Grav\Common\Form\FormFlash::getSessionTmpDir()

### ISSUE THREAD

**Issue by everlaat** [bleutzinn/grav-plugin-add-page-by-form#44]
Plugin version: 2.3.0
Grav version: 1.6.11
Form Version: 3.0.7

---
form configuration;
```
-
            name: images
            label: 'Images to upload'
            type: file
            multiple: true
            accept:
                - 'image/*'
            destination: '@self'
```

As soon as I try to upload an image, the uploader widget displays the error;
```
Call to undefined method Grav\Common\Form\FormFlash::getSessionTmpDir()
```

And although the form shows the thumbnail of the selected image the actual image is not uploaded.
