### ISSUE TITLE
Redirect to @self not working

### ISSUE THREAD

**Issue by pd-giz-dave** [bleutzinn/grav-plugin-add-page-by-form#48]
I have setup a form that uses redirect: '@self' but its not working. What happens is this:

1. The browser is correctly given the new page slug
2. The page exists in the file system
3. Grav reports page not found 404
4. Wait a little while
5. Refresh the page and its there

This smells of a caching issue but I have been unable to find out where this all happens, I'm niaive about Grav and don't where to look to diagnose/fix the issue. I'm quite happy to diagnose/fix this but I need some pointers on where to look. Can you give me any hints?

**Comment by bleutzinn** [comment]
Unfortunately I can't replicate the behaviour you described.

Using this form page and with the standard Grav caching on (method Markdown + Yaml file timestamps) the page is created and Grav directly redirects to the new page. Make sure the value of the redirect is `'@self'`.
```
title: 'Add Blog Post'
template: form
pageconfig:
    parent: /blog
    include_username: true
    overwrite_mode: true
pagefrontmatter:
    template: item
    title: 'My new Blog post'
    taxonomy:
        category: blog
        tag:
            - journal
            - guest
form:
    name: addpage.blogpost
    fields:
        -
            name: author
            label: Author
            type: text
        -
            name: title
            label: 'Post Title'
            type: text
        -
            name: taxonomy.tag
            label: 'Tags (comma separated)'
            type: text
        -
            name: content
            label: 'Post Content'
            type: textarea
            size: long
            classes: editor
        -
            name: images
            label: 'Images to upload'
            type: file
            multiple: true
            accept:
                - 'image/*'
            validate:
                required: false
            destination: '@self'
        -
            name: honeypot
            type: honeypot
    buttons:
        -
            type: submit
            value: Submit
    process:
        -
            addpage: null
        -
            redirect: '@self'
```

**Comment by pd-giz-dave** [comment]
That's odd. I've tried various caching options and it makes no difference. My form is very simple, its this:
======================
---
title: 'Add News Item'
template: form
routable: true
visible: true
access:
    site.editable: true
pageconfig:
    parent: /news
    include_username: true
    overwrite_mode: false
pagefrontmatter:
    template: item
    title: 'News item'
    taxonomy:
        category: news
    editable-simplemde:
        self: true
form:
    name: addpage.newsitem
    fields:
        -
            name: title
            label: 'News Title'
            type: text
    buttons:
        -
            type: submit
            value: Add News Item
    process:
        -
            addpage: null
        -
            redirect: '@self'
---

## Add News Item

Set the news item title, select <code>Add News Item</code>, then edit the page created.
================

My environment is a local apache2 server running under ubuntu/mate 19.10

I can't debug this in the normal way because as soon as a breakpoint is hit in the PHP the delay is enough to make it work! Very frustrating.

Thanks for trying it.

**Comment by pd-giz-dave** [comment]
Sorry for odd format, something messed with my text!

**Comment by bleutzinn** [comment]
Can you please again edit your comment and enclose the code in triple backticks?

**Comment by pd-giz-dave** [comment]
Ah, I get it, its markdown aware:
```
---
title: 'Add News Item'
template: form
routable: true
visible: true
access:
    site.editable: true
pageconfig:
    parent: /news
    include_username: true
    overwrite_mode: false
pagefrontmatter:
    template: item
    title: 'News item'
    taxonomy:
        category: news
    editable-simplemde:
        self: true
form:
    name: addpage.newsitem
    fields:
        -
            name: title
            label: 'News Title'
            type: text
    buttons:
        -
            type: submit
            value: Add News Item
    process:
        -
            addpage: null
        -
            redirect: '@self'
---

## Add News Item

Set the news item title, select <code>Add News Item</code>, then edit the page created.
```
