### ISSUE TITLE
Select field not saving values when multiple: true

### ISSUE THREAD

**Issue by julienbenisty** [bleutzinn/grav-plugin-add-page-by-form#53]
Hi @bleutzinn ,

while working on a front-end form using this plugin, I ran into the following issue.
A select field set to `multiple: true` was not saving the selected values.

Here is the field from my template file:
```
name: photo_type
type: select
label: select multiple options
multiple: true
options:
      option1: 'option1'
      option2: 'option2'
      option3: 'option3'
      option4: 'option4'
```
All other fields are saved correctly but this one. This is what shows in the frontmatter of the generated file:
`photo_type: ' '`

The issue was found using Grav v1.6.24 with Add Page By Form v3.0.0 running on PHP 7.3.9.
I also got the same error using Grav v1.7.0-rc.10 with Add Page By Form v3.0.0 running on PHP 7.3.9 as well.
Here are the plugin config:
```
enabled: true
date_display_format: 'F jS Y'
default_title: 'My New Page'
default_content: null
overwrite_mode: '0'
include_username: true
auto_taxonomy_types: false
use_editor_class: true
physical_template_name: false
```

It's good to note that value gets saved properly when `multiple: false`.

Let me know if you need more info or testing. And if I can help in any way.
