### ISSUE TITLE
overwrite_mode: true or overwrite_mode: edit show ERROR in Add Page by Form Plugin: Variable 'slug' is empty

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [bleutzinn/grav-plugin-add-page-by-form#58]
Hi.
When you configure your form with orverwrite_mode in true or edit mode, if you write one post with the same title, the form shows ERROR in Add Page by Form Plugin: Variable 'slug' is empty.

Is this a bug or is necessary configure it in the other way?
Thanks.

**Comment by bleutzinn** [comment]
Hi, sorry for responding so late. I can't replicate it. Do you still have this problem?

If so please tell me which versions of Grav and this plugin you are using. And your form page is also very helpful in finding the problem.

**Comment by pmoreno-rodriguez** [comment]
Hi @bleutzinn .
I'm trying the page form again, and I've realized the problem only happens when overwrite_mode is in edit mode. In edit mode the errors with '**Variable slug is empy**' keeps showing.

With true option it creates a new page (add 1, 2, 3, etc to folder name). I think it shouldn't show in true mode. I think it should overwrite the previous post.

My Grav version 1.6.31 and the plugin version is 3.0.3.

I'll try to configure an access to a example site for you. Can you give me some way to send you the access data to my test site?

**Comment by pmoreno-rodriguez** [comment]
Sorry. In overwrite_mode=true it works fine. It overwrite the previous post

**Comment by pmoreno-rodriguez** [comment]
Hi again.
This is de code of page.md to add new post:
```
title: 'Añadir artículo de Blog'
published: true
body_classes: 'modular header-lite fullwidth'
visible: false
template: form
twitterenable: false
twittercardoptions: summary
facebookenable: false
access:
    site.login: true
rememberme:
    enabled: false
redirect_after_logout: true
route_after_logout: /
bg_img: blog-header3.jpg
onpage_menu: false
bg_color: '#B4B093'
pageconfig:
    parent: /blog
    include_username: false
    overwrite_mode: edit
    use_editor_class: true
pagefrontmatter:
    template: item
    title: 'My new Blog post'
    taxonomy:
        category: blog
        tag: {  }
    body_classes: 'header-lite fullwidth blogstyling'
form:
    name: add_page.blogpost
    fields:
        -
            name: author
            label: Autor
            type: text
        -
            name: title
            label: 'Título del artículo'
            type: text
        -
            name: taxonomy.tag
            label: 'Etiquetas (separadas por comas)'
            type: text
        -
            name: content
            label: 'Contenido del artículo'
            type: textarea
            size: long
            classes: editor
        -
            name: images
            label: 'Subir imagen de cabecera'
            type: file
            multiple: false
            accept:
                - 'image/*'
        -
            name: honeypot
            type: honeypot
    buttons:
        -
            type: submit
            value: Enviar
    process:
        -
            add_page: true
        -
            redirect: /blog
```
If I want to add an article that already exists, like this:

![Selection_047](https://user-images.githubusercontent.com/60596353/104494663-05e2a080-55d7-11eb-9198-61fde077e7c1.png)

With **edit** option in overwrite_mode you can see the error in the image attached.:

![Selection_048](https://user-images.githubusercontent.com/60596353/104494666-0713cd80-55d7-11eb-94c6-577b74c37814.png)
