### ISSUE TITLE
Pagefrontmatter with "content" attribute is not created in the final page

### ISSUE THREAD

**Issue by arifrifai** [bleutzinn/grav-plugin-add-page-by-form#63]
I try to create blog list page like this:
```
pagefrontmatter:
    template: blog
    content:
        items:
            - '@self.children'
        limit: 5
        order:
            by: date
            dir: desc
```
but the `content` attribute is not created in the header, because the form use the same name
